replicas: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: skaiaksreg.azurecr.io/bob-the-bot
  tag: 159
  pullPolicy: IfNotPresent

pods:
  name: http
  port: 8080

resources:
  limits:
    cpu: 1
    memory: 2500Mi
  requests:
    cpu: 400m
    memory: 700Mi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

config:
  enabled: false

secrets:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false

litellm:
  enabled: true
  name: litellm
  image:
    repository: skaiaksreg.azurecr.io/litellm
    tag: latest
  resources:
    requests:
      cpu: 500m
      memory: 400Mi
    limits:
      cpu: 1
      memory: 500Mi
  configMap:
    name: litellm-config
  service:
    type: ClusterIP
    port: 4000