apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob-the-bot
  labels: {{ include "bob-the-bot.labels" . | nindent 4 }}
spec:
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{ include "bob-the-bot.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "bob-the-bot.labels" . | nindent 8 }}
    spec:
      containers:
      - name: bob-the-bot
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - name: {{ .Values.pods.name }}
            containerPort: {{ .Values.pods.port }}
            protocol: TCP
        envFrom:
          - secretRef:
              name: bob-secrets
        resources: {{- toYaml .Values.resources | nindent 12 }}