apiVersion: v1
kind: Service
metadata:
  name: "bobthebot"
  labels: {{ include "bob-the-bot.labels" . | nindent 4 }}
spec:
  selector: {{ include "bob-the-bot.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.pods.port }}
  type: {{ .Values.service.type }}